<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Playlist Musical</title>
    <link rel="stylesheet" href="css/estilos.css">
</head>
<body>
<header>
    <h1>🎵 Playlist Musical</h1>
    <nav>
        <a href="/dashboard/WEB2/TP2/index.php?action=home">Inicio</a> |
        <a href="/dashboard/WEB2/TP2/index.php?action=agregar">Agregar canción</a> |
        <a href="/dashboard/WEB2/TP2/index.php?action=logout">Cerrar sesión</a>
    </nav>
</header>
<main>