<h2>Agregar canción</h2>

<form action="index.php?action=guardarNueva" method="POST">
    <label for="nombre_cancion">Nombre:</label>
    <input type="text" name="nombre_cancion" id="nombre_cancion" required><br>

    <label for="anio">Año:</label>
    <input type="number" name="anio" id="anio" required><br>

    <label for="album">Album:</label>
    <input type="text" name="album" id="album" required><br>

    <label for="duracion">Duración:</label>
    <input type="text" name="duración" id="duracion" required><br>

    <label for="mood_cancion">Mood:</label>
    <input type="text" name="mood_cancion" id="mood_cancion" required><br>

    <label for="genero_musical">Género:</label>
    <input type="text" name="genero_musical" id="genero_musical" required><br>

    <label for="autor">Autor:</label>
    <input type="text" name="autor" id="autor" placeholder="Escribí el autor" required><br>

    <button type="submit">Guardar</button>
</form>